### ISSUE TITLE
"single click selects all" back in 78.0.1 and script does not fix this anymore

### ISSUE THREAD

**Issue by wmzart** [SebastianSimon/firefox-selection-fix#1]
I experience with the update from today to 78.0.1, that the single click bug (or feature?) comes back unfortunately and this script does not fix this.

Am I the only one experiencing this?

**Comment by SebastianSimon** [comment]
It still works for me on Firefox Nightly 80.0a1. Same thing as always: after Firefox has installed the updates (you may need to start and close Firefox again after updating), run the script. The Firefox `.desktop` file needs the `--purgecaches` flag, too. Did your desktop configuration file change with the update?

**Comment by wmzart** [comment]
Thanks for the --purgecaches remark. Indeed it was overwritten and therefore it did not work.

Maybe something like the following can be added to the script in order to fix the firefox.desktop file.

Obviously the file location of firefox.desktop varies between systems. So this would need to be platform independant.

`
#!/bin/bash
[ "$UID" -eq 0 ] || { echo "This script must be run as root."; exit 1;}

FFDESKTOP="/usr/share/applications/firefox.desktop"
sed -i 's/Exec=firefox -private-window/Exec=firefox --purgecaches -private-window/g' ${FFDESKTOP}
sed -i 's/Exec=firefox -new-window/Exec=firefox --purgecaches -new-window/g' ${FFDESKTOP}
sed -i 's/Exec=firefox --purgecaches %u/Exec=firefox --purgecaches --purgecaches %u/g' ${FFDESKTOP}
`

After adding the --purgecaches option it works again.

**Comment by SebastianSimon** [comment]
Yes, yes, of course! If I could add it, I would, and making it platform independent is the key here! Mine is `~/.local/share/applications/userapp-Nightly-RTEQFZ.desktop` which already is a nightmare to figure out manually. As soon as I figure out, how to efficiently search for this file, and have the time to do it, I’ll update the script.

For now, this issue is closed.

**Comment by SebastianSimon** [comment]
After giving up on the headache of finding an [efficient][super-user-find-locate] and [platform-independent][update-gnome-applications-menu] way of finding the right `*.desktop` file, I found a much easier way.

Re-reading the blog articles mentioned in the [Super User answer][super-user], there are two other ways to purge the caches. The `export MOZ_PURGE_CACHES=1` option doesn’t really work for this use-case, as the environment variable won’t be applied when executing the command in the `*.desktop` file.

The other option stated _“Use the `.purgecaches` file”_ which I find very unclear. I don’t have such a file, so I assume, I have to create it. But what to put in the file? Where to put the file?

I guessed _empty file_, and after trying two possible locations, I found out that putting an empty `.purgecaches` file in the `browser` directory actually worked! Now a simple `touch $firefox_dir/browser/.purgecaches` line is added to the script.
The `--purgecaches` option is no longer necessary for the `*.desktop` file.

I’ve updated the script now. It also now has a change regarding file permissions: being root isn’t always required for running the script, but if it is for you (any of you), edit the script and uncomment the line that says `require_root=true`.


  [super-user-find-locate]: https://superuser.com/q/341232/751213
  [update-gnome-applications-menu]: https://gist.github.com/KSXGitHub/445795a264248d55ce3f2eda0fb6dbbb
  [super-user]: https://superuser.com/a/1559926/751213

**Comment by wmzart** [comment]
I am a bit confused after the script finishes, that it ends suddenly in /tmp

Could you improve the script further to stay in the directory where it started from. For example something like this:

```
# save current directory to revert to when finished
bakdir=$(pwd)
...
# return to directory where started from
cd ${bakdir}
```

In case of any error, it will likely not return to the original directory then, but at least this should help with the terminal.

**Comment by SebastianSimon** [comment]
Yes, I could do that.

I need to do some research on how to _end_ shell scripts such that the terminal will be left open at the end (so you could see the final output), even when you execute the script from a file manager. Currently, I think a `bash` at the end is just fine. Users can just <kbd>Ctrl</kbd>+<kbd>D</kbd> their way out at the end.

I’ll test the script later on and upload an improved version.

**Comment by wmzart** [comment]
I am sorry, I could not see very well on my screen. Obviously you are right. I corrected it above. You can delete your posting, if you want, not to cause more confusion.
