### ISSUE TITLE
What about browser.urlbar.doubleClickSelectsAll?

### ISSUE THREAD

**Issue by Ketchup901** [SebastianSimon/firefox-selection-fix#9]
I've used your instructions on Super User and it's great. There's just one problem. Since single clicking no longer selects the entire thing, neither does double clicking, which was the behavior in old Firefox. Is it possible to bring back the bevavior of browser.urlbar.doubleClickSelectsAll = true?

**Comment by SebastianSimon** [comment]
Oh, can’t believe I never tested this! I’ll see what I can do.

**Comment by SebastianSimon** [comment]
Wow, it’s been over a month already. Sorry, for the delay…

There are now three issues — #7, #10, and yours, #9 — which ask for some features beyond the narrow scope of restoring the `clickSelectsAll` behavior. This one’s about `doubleClickSelectsAll`, #10 is about the selection clipboard, and #7 (partially) is about focus appearance. Widening the scope has been a plan of mine, though this requires renaming the repo and some interface for selecting which changes should be applied (I’ve thought about an `--option` flag for the script and maybe a web interface that downloads a shell script with the chosen presets).

But there are still a few open questions, e.g. how should `clickSelectsAll` and `doubleClickSelectsAll` interact? I’ll test this later today.

**Comment by SebastianSimon** [comment]
Commit 361c393 now introduces an option to enable the old `doubleClickSelectsAll` behavior (either edit the script to `[options|doubleClickSelectsAll]='on'`, execute it as `./fixfx-selection.sh -o doubleClickSelectsAll`, or wait a few days for the web interface to be finished). I looked at the old Firefox source code for this, so this should behave exactly the same as in the past.

It also doesn’t conflict with `preventClickSelectsAll`; disabling it requires either a manual source code edit to `[options|preventClickSelectsAll]=''`, executing the script as `./fixfx-selection.sh -o doubleClickSelectsAll -o preventClickSelectsAll=`, or, again, the web interface. But having both singleClickSelectsAll and doubleClickSelectsAll enabled sure is confusing…
